### ISSUE TITLE
Events structure

### ISSUE THREAD

**Issue by madmuffin1** [jesusfreaks/fs-rest-service#2]
GET /v1/events
    
    [{ 
        id: Long
        type: String // any of: Concert, Workshop, Seminar, Service, tbc
        name: String
        description: String
        startTime: Long // timestamp (local or UTC? tbd)
        endTime: Long // idem
        artist: Long
        location: Long
        state: String // any of: Past, Upcoming, Canceled
    }]

**Comment by dodophoenix** [comment]
* maybe add some type (Concert | Workshop | ...)
To allow Filtering

* states (past / upcoming) should be calculated offline as we have no constant connection 

* canceled can be a boolean flag

**Comment by madmuffin1** [comment]
>    maybe add some type (Concert | Workshop | ...) to allow Filtering

agreed

>    states (past / upcoming) should be calculated offline as we have no constant connection

yes, but in addition to that we might want to mark some events as past at the time of download. 

>    canceled can be a boolean flag

I'd rather go for some kind of fake-enum, this way we could also have a state like Additional (for gigs that are added later-on)

**Comment by dodophoenix** [comment]
* should never return Id's, instead return links where we can retrieve dependet objects

**Comment by madmuffin1** [comment]
Does that work well with the local caching? Will all subsequently occurable calls be made at once?

**Comment by nschwalbe** [comment]
Startdate/ enddate should be saved in UTC but will be delivered in Timezone 'Europe/Berlin'.
Enddate is optional and can be on the next day.
